title: Binghuan Wu (吴秉寰) # your name (or website title) here
logo: "/images/personal photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A dedicated engineer
  <br><br>
  A motivated future entrepreneur
  <br><br>
  <a href="https://www.linkedin.com/in/warner-ng-662312326/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/warner-ng">View My GitHub Profile</a> 
  <br><br>
  <a href="/pdf/Warner's CV.pdf" target="_blank">My CV</a> 

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
